//1. Getting alll appointments
export const GET_ALL_APPOINTMENTS = "GET_ALL_APPOINTMENTS"; // for request
export const GET_ALL_APPOINTMENTS_SUCCESS = "GET_ALL_APPOINTMENTS_SUCCESS"; // on success
export const GET_ALL_APPOINTMENTS_FAILURE = "GET_ALL_APPOINTMENTS_FAILURE"; // on failure

export const GET_ALL_APPOINTMENTS_BY_CLINIC = "GET_ALL_APPOINTMENTS_BY_CLINIC"; // for request
export const GET_ALL_APPOINTMENTS_BY_CLINIC_SUCCESS = "GET_ALL_APPOINTMENTS_BY_CLINIC_SUCCESS"; // on success
export const GET_ALL_APPOINTMENTS_BY_CLINIC_FAILURE = "GET_ALL_APPOINTMENTS_BY_CLINIC_FAILURE"; // on failure
